### ISSUE TITLE
[PE-D][Tester C] Case insensitivity when adding authors using catalog command

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2113-T10-3/tp#131]
![image.png](https://raw.githubusercontent.com/hzxnancy/ped/main/files/3fde3561-9f25-45e5-96dc-89ca17161702.png)

When adding a new author name, the system creates a new entry even if the name is identical, but with different casing. Would it be better to make the checking of dulplicate authors case-sensitive to prevent adding duplicate entries with varying casing?

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: hzxnancy/ped#1

**Comment by xenthm** [comment]
Grouped together.
