### ISSUE TITLE
[PE-D][Tester A] Duplicated Author

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2113-T10-3/tp#133]
![image.png](https://raw.githubusercontent.com/Littleme1032/ped/main/files/035a03cb-591c-4b48-a333-bcf756dacb8d.png)

 able to put user with the same name, i feel it should be reflected as duplicated as they are the same name but just different casing. 

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: Littleme1032/ped#1

**Comment by xenthm** [comment]
Grouped together.
