### ISSUE TITLE
[PE-D][Tester C] Case insensivity check for manga dulplication

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2113-T10-3/tp#134]
![image.png](https://raw.githubusercontent.com/hzxnancy/ped/main/files/a6c5f15e-2da5-46aa-af04-c927733a8819.png)

Similar to checking of dulplicate authors, would it be better if the checking of dulplicate mangas be case sensitive to prevent multiple entires of the same manga but with different casing? 

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: hzxnancy/ped#2

**Comment by xenthm** [comment]
Grouped together.
