### ISSUE TITLE
[PE-D][Tester C] Lack of date validation when adding deadline

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2113-T10-3/tp#141]
![image.png](https://raw.githubusercontent.com/hzxnancy/ped/main/files/69fd4bdd-966a-4c1f-b511-01f3c57c9e88.png)

Currently, the program doesn't throw an error for invalid dates. Hence, would it be better to throw an error when the date input is invalid?

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: hzxnancy/ped#3

**Comment by xenthm** [comment]
Grouped together.
