### ISSUE TITLE
[PE-D][Tester C] Incorrect labelling of abstract classes and methods

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2113-T10-3/tp#148]
![image.png](https://raw.githubusercontent.com/hzxnancy/ped/main/files/de218fe4-2294-46b6-baf5-84d2641914e3.png)

The diagram is very neat and comprehensive, but it could be further improved with the correct abstract notation! Abstract notation is surrounded by curly braces like this, {abstract}

-------------
Labels: `type.DocumentationBug` `severity.VeryLow`
original: hzxnancy/ped#6

**Comment by xenthm** [comment]
Grouped together.

**Comment by sarahchow03** [comment]
Issue resolved.
