### ISSUE TITLE
[PE-D][Tester C] Didn't deactivate the sequence diagram

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2113-T10-3/tp#153]
![image.png](https://raw.githubusercontent.com/hzxnancy/ped/main/files/6274c847-1d9e-46b4-9aa4-6a16fcf88a62.png)

For the Saving Data Sequence Diagram, do remember to deactivate the Tantou activation bar after executing the saving sequence! 

-------------
Labels: `type.DocumentationBug` `severity.VeryLow`
original: hzxnancy/ped#10

**Comment by xenthm** [comment]
Grouped together.
