### ISSUE TITLE
[PE-D][Tester A] invalid date 

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2113-T10-3/tp#154]
![image.png](https://raw.githubusercontent.com/Littleme1032/ped/main/files/5cc01229-3c38-4042-b6cf-2b64fe50263c.png)

allows invalid date input 

-------------
Labels: `type.FeatureFlaw` `severity.Medium`
original: Littleme1032/ped#5

**Comment by xenthm** [comment]
Grouped together.
