### ISSUE TITLE
[Post PE-D] Diagram issue in Developer Guide

### ISSUE THREAD

**Issue by sarahchow03** [AY2425S1-CS2113-T10-3/tp#160]
Refers to issues of either ambiguity, non-standard adherence of course standards, or unclear diagrams.

Mentioned in #153 and #145.

**Comment by xenthm** [comment]
# ADDITIONAL ISSUE
![image](https://github.com/user-attachments/assets/146e1dd6-f5a7-462c-b806-74328e6cbff5)
Should be using dotted line for return.

**Comment by xenthm** [comment]
To save properly, copy the diagram from the puml preview window and paste directly into desired folder.

**Comment by xenthm** [comment]
# Additional
- [ ] Update Storage diagram with changes made in #177
