### ISSUE TITLE
JUnit tests are modifying local copy of catalog.json

### ISSUE THREAD

**Issue by xenthm** [AY2425S1-CS2113-T10-3/tp#55]
# Issue
When `gradlew build` is run to build the project with Gradle, JUnit tests are run. The JUnit tests for commands that modify the `authorList` (and hence will save the changes to the data file) are using the local copy of `catalog.json` to perform tests. This overrides the contents of the file. 

# Potential fixes
1. Set up `dataFile` in `Storage` to be a different path before running any JUnit test for commands that modify the `authorList`
2. Change the implementation of `Storage` to instantiate it differently for JUnit tests

# Contents of `catalog.json` after `gradlew build` is run
The `authorList` serialized here is from a JUnit test. 
![image](https://github.com/user-attachments/assets/4bcf13b3-344e-4d72-8ccc-7fa948de831d)

**Comment by averageandyyy** [comment]
Possible to read/load from one file but write the save file to another destination to prevent the overwriting? Just an idea.

**Comment by xenthm** [comment]
>Possible to read/load from one file but write the save file to another destination to prevent the overwriting? Just an idea.

Do you mean just for tests? Because if we do this for the main app we need to get the user to indicate where they last saved their data. 

>1. Set up dataFile in Storage to be a different path before running any JUnit test for commands that modify the authorList

Actually, option 1 is already implemented, but only in `StorageTest`. 

![image](https://github.com/user-attachments/assets/122bd2f1-5700-4923-81f5-b58405715a26)

So all we need to do it extend it so that all tests do this.

**Comment by averageandyyy** [comment]
yup just for tests only, basically like the IO test where we have actual and expected as two separate files.

**Comment by xenthm** [comment]
Alright, I did that for `StorageTest`. For future development it is probably worth it to set a global JUnit setting so that all tests use a different data file. However, it needs to be deconflicted with `testCatalog.json` which is needed by `StorageTest`. It shouldn't be changed.

**Comment by xenthm** [comment]
Updated severity as this only affects developers that use `gradlew build`.

**Comment by xenthm** [comment]
I found a fix on the JUnit 5 [docs](https://junit.org/junit5/docs/current/user-guide/#launcher-api-launcher-session-listeners-custom).
