### ISSUE TITLE
Fix diagram issues in DG from #90

### ISSUE THREAD

**Issue by xenthm** [AY2425S1-CS2113-T10-3/tp#93]
>Good job so far, but this needs some work! Also include the config file I made for PlantUML Class and Sequence diagrams from #76 for standardisation!

_Originally posted by @xenthm in https://github.com/AY2425S1-CS2113-T10-3/tp/pull/90#pullrequestreview-2401563381_

**Comment by sarahchow03** [comment]
On top of the .config file addition, the AddScheduleCommand should adhere to the changes made in this PR [#116]. This refers to placing sequence diagram into a sd AddScheduleCommand frame.
